<?php

namespace App\Platform\Services;

/**
 * Reads an uploaded invoice (PDF or Word) and extracts the fields that
 * matter for a renewal (amount, issued/due dates). Real invoices are
 * almost always text-based documents (generated by billing software), not
 * scanned images, so text extraction + an AI pass to structure it covers
 * the MVP case without needing true image OCR (Tesseract, a cloud OCR
 * API, Claude vision) — a heavier dependency this doesn't need yet.
 */
class InvoiceOcrService
{
    public static function extract(string $absolutePath, int $userId, string $workerSlug, ?string $txId = null, ?int $deploymentId = null, string $extension = 'pdf'): array
    {
        $text = match (strtolower($extension)) {
            'docx'  => self::extractWordText($absolutePath),
            default => self::extractPdfText($absolutePath),
        };

        if ($text === null) {
            return ['error' => $extension === 'docx'
                ? 'Could not read this Word document.'
                : 'Could not read this PDF — it may be a scanned image rather than a text-based invoice.'];
        }

        if ($text === '') {
            return ['error' => 'No readable text found in this file.'];
        }

        $claude = app(ClaudeService::class);
        $claude->configure(ClaudeService::platformDefaultModel(), $userId, $workerSlug);

        // Override key matches the pipeline stage ('request_invoice'), not the
        // usage-log tag below — that's how it shows up as an editable card on
        // the Configure page, which lists prompts by pipeline stage key.
        $override = $deploymentId
            ? \App\Platform\SDK\UnitPlatform::getPromptOverride($deploymentId, 'request_invoice') ?? []
            : [];

        $system = $override['system'] ?? ('You extract structured fields from invoice text. Return valid JSON only, no extra text. '
            . 'Use null for any field you cannot find — never guess.');

        $defaultPrompt = <<<PROMPT
Extract these fields from the invoice text below:
{
  "amount": null,
  "currency": null,
  "issued_date": null,
  "due_date": null,
  "invoice_number": null
}

Dates in YYYY-MM-DD format. Amount as a plain number (no currency symbol).

INVOICE TEXT:
{$text}
PROMPT;

        $prompt = !empty($override['user'])
            ? str_replace('{INVOICE_TEXT}', $text, $override['user'])
            : $defaultPrompt;

        $maxTokens = $override['max_tokens'] ?? 512;

        try {
            return $claude->ask($system, $prompt, $maxTokens, $txId, 'invoice_ocr');
        } catch (\Throwable $e) {
            return ['error' => 'Could not extract invoice details automatically.'];
        }
    }

    private static function extractPdfText(string $absolutePath): ?string
    {
        try {
            $parser = new \Smalot\PdfParser\Parser();
            return trim($parser->parseFile($absolutePath)->getText());
        } catch (\Throwable $e) {
            return null;
        }
    }

    private static function extractWordText(string $absolutePath): ?string
    {
        try {
            $phpWord = \PhpOffice\PhpWord\IOFactory::load($absolutePath);
            $text    = '';
            foreach ($phpWord->getSections() as $section) {
                foreach ($section->getElements() as $element) {
                    if (method_exists($element, 'getText')) {
                        $text .= $element->getText() . "\n";
                    } elseif (method_exists($element, 'getElements')) {
                        // TextRun — a paragraph made of multiple runs
                        foreach ($element->getElements() as $run) {
                            if (method_exists($run, 'getText')) $text .= $run->getText();
                        }
                        $text .= "\n";
                    }
                }
            }
            return trim($text);
        } catch (\Throwable $e) {
            return null;
        }
    }
}
