<?php

namespace App\Platform\Services;

/**
 * Reads an uploaded invoice PDF and extracts the fields that matter for a
 * renewal (amount, issued/due dates). Real invoices are almost always
 * text-based PDFs (generated by billing software), not scanned images, so
 * text extraction + an AI pass to structure it covers the MVP case without
 * needing true image OCR (Tesseract, a cloud OCR API) — a heavier
 * dependency this doesn't need yet.
 */
class InvoiceOcrService
{
    public static function extract(string $absolutePath, int $userId, string $workerSlug, ?string $txId = null): array
    {
        try {
            $parser = new \Smalot\PdfParser\Parser();
            $text   = trim($parser->parseFile($absolutePath)->getText());
        } catch (\Throwable $e) {
            return ['error' => 'Could not read this PDF — it may be a scanned image rather than a text-based invoice.'];
        }

        if ($text === '') {
            return ['error' => 'No readable text found in this PDF.'];
        }

        $claude = app(ClaudeService::class);
        $claude->configure(ClaudeService::platformDefaultModel(), $userId, $workerSlug);

        $system = 'You extract structured fields from invoice text. Return valid JSON only, no extra text. '
            . 'Use null for any field you cannot find — never guess.';

        $prompt = <<<PROMPT
Extract these fields from the invoice text below:
{
  "amount": null,
  "currency": null,
  "issued_date": null,
  "due_date": null,
  "invoice_number": null
}

Dates in YYYY-MM-DD format. Amount as a plain number (no currency symbol).

INVOICE TEXT:
{$text}
PROMPT;

        try {
            return $claude->ask($system, $prompt, 512, $txId, 'invoice_ocr');
        } catch (\Throwable $e) {
            return ['error' => 'Could not extract invoice details automatically.'];
        }
    }
}
