<?php

namespace App\Workers\NUX\Jobs;

use App\Platform\SDK\UnitPlatform;
use App\Platform\SDK\WorkerOutput;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class DraftPostJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $tries   = 3;
    public int $timeout = 60;

    public function backoff(): array
    {
        return [30, 60, 120];
    }

    public function __construct(public string $txId) {}

    public function handle(): void
    {
        $input = UnitPlatform::getInput($this->txId);
        UnitPlatform::setStatus($this->txId, 'drafting');

        $read      = $input->stage('read_post');
        $classify  = $input->stage('classify');
        $repurpose = $input->stage('repurpose');
        $media     = $input->stage('media');

        $copies         = $repurpose['repurposed_copies'] ?? [];
        $sourcePlatform = $read['platform'] ?? 'linkedin';
        $topic          = $classify['topic'] ?? '';
        $postUrl        = $read['post_url'] ?? null;
        $imageUrl       = $media['image_url'] ?? null;
        $imagePath      = $media['image_path'] ?? null;
        $imageGenerated = (bool) ($media['image_generated'] ?? false);

        // Build email subject
        $channelList  = implode(' + ', array_column($copies, 'channel'));
        $topicLabel   = $topic ? " — {$topic}" : '';
        $emailSubject = "NUX: Repurposed for {$channelList}{$topicLabel}";

        // Build email body (plain HTML)
        $body  = "<p><strong>Original post</strong> ({$sourcePlatform})";
        $body .= $postUrl ? ": <a href=\"{$postUrl}\">{$postUrl}</a>" : '';
        $body .= "</p>\n<hr>\n";

        foreach ($copies as $copy) {
            $channel   = strtoupper($copy['channel'] ?? '');
            $copyText  = htmlspecialchars($copy['copy'] ?? '', ENT_QUOTES, 'UTF-8');
            $charCount = $copy['char_count'] ?? mb_strlen($copy['copy'] ?? '');
            $body .= "<h3>{$channel}</h3>\n";
            $body .= "<blockquote style=\"white-space:pre-wrap;font-family:monospace;font-size:14px\">{$copyText}</blockquote>\n";
            $body .= "<p style=\"color:#888;font-size:12px\">{$charCount} characters</p>\n";
        }

        if ($imageGenerated && $imageUrl) {
            $body .= "<hr>\n<h3>Generated Image</h3>\n";
            $body .= "<img src=\"{$imageUrl}\" alt=\"NUX generated image\" style=\"max-width:600px;border-radius:8px\">\n";
            if ($imagePath) {
                $localUrl = asset('storage/' . $imagePath);
                $body .= "<p style=\"font-size:12px;color:#888\">Also saved locally: <a href=\"{$localUrl}\">{$localUrl}</a></p>\n";
            }
        }

        $body .= "<hr>\n<p style=\"color:#888;font-size:12px\">Generated by NUX · UNIT Platform</p>\n";

        // One-line summary for the transaction card
        $channelNames = implode(', ', array_column($copies, 'channel'));
        $draftSummary = "Repurposed {$sourcePlatform} post for {$channelNames}"
            . ($imageGenerated ? ' + image' : '');

        UnitPlatform::commitOutput($this->txId, new WorkerOutput(
            stage:  'draft_post',
            status: 'drafting',
            data:   [
                'email_subject' => $emailSubject,
                'email_body'    => $body,
                'draft_summary' => $draftSummary,
            ],
        ));

        UnitPlatform::log('nux', $this->txId, 'draft_compiled', [
            'channels'       => $channelNames,
            'image_included' => $imageGenerated,
        ]);

        PushToGmailJob::dispatch($this->txId)->onQueue($input->queue);
    }

    public function failed(\Throwable $e): void
    {
        UnitPlatform::setStatus($this->txId, 'failed');
        UnitPlatform::log('nux', $this->txId, 'job_failed', [
            'job' => 'DraftPostJob', 'error' => $e->getMessage(),
        ], 'error');
    }
}
